version: '3.4'
services:
  employee_management_system:
    image: employee_management_system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=EmployeeManagement;User Id=sa;Password=12345;
      - Jwt__Key=your_secret_key
      - Jwt__Issuer=your_issuer
      - Jwt__Audience=your_audience
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=12345
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"