version: '3.4'
services:
  employee_management_system:
    image: employee_management_system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=EmployeeManagement;User Id=sa;Password=your_password;
      - Jwt__Key=your_secret_key
      - Jwt__Issuer=EmployeeManagementSystem
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=your_password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"